version: 2
jobs:
  lint:
    docker:
      - image: wata727/tflint:0.9.2
    steps:
      - checkout
      - run:
          name: lint
          command: tflint
  validate:
    docker:
      - image: hashicorp/terraform:0.12.5
    steps:
      - checkout
      - run: terraform init
      - run: terraform validate
