version: 2
jobs:
  build:
    docker:
      - image: wata727/tflint:0.13.1
    steps:
      - checkout
      - run:
          name: lint
          command: tflint
  validate:
    docker:
      - image: hashicorp/terraform:0.12.16
    steps:
      - checkout
      - run:
          name: init
          command: terraform init
      - run:
          name: validate
          command: terraform validate
workflows:
  version: 2
  build_and_validate:
    jobs:
      - build
      - validate
